cnf(synonym_m_D_glucose_6_phosphate_m_alpha_D_Glucose_6_phosphate_c_ce, axiom, ( met(m_D_glucose_6_phosphate, c_ce) | ~met(m_alpha_D_Glucose_6_phosphate, c_ce) )).
cnf(synonym_m_alpha_D_Glucose_6_phosphate_m_D_glucose_6_phosphate_c_ce, axiom, ( met(m_alpha_D_Glucose_6_phosphate, c_ce) | ~met(m_D_glucose_6_phosphate, c_ce) )).
cnf(synonym_m_D_glucose_6_phosphate_m_alpha_D_Glucose_6_phosphate_c_c, axiom, ( met(m_D_glucose_6_phosphate, c_c) | ~met(m_alpha_D_Glucose_6_phosphate, c_c) )).
cnf(synonym_m_alpha_D_Glucose_6_phosphate_m_D_glucose_6_phosphate_c_c, axiom, ( met(m_alpha_D_Glucose_6_phosphate, c_c) | ~met(m_D_glucose_6_phosphate, c_c) )).
cnf(synonym_m_D_glucose_6_phosphate_m_alpha_D_Glucose_6_phosphate_c_e, axiom, ( met(m_D_glucose_6_phosphate, c_e) | ~met(m_alpha_D_Glucose_6_phosphate, c_e) )).
cnf(synonym_m_alpha_D_Glucose_6_phosphate_m_D_glucose_6_phosphate_c_e, axiom, ( met(m_alpha_D_Glucose_6_phosphate, c_e) | ~met(m_D_glucose_6_phosphate, c_e) )).
cnf(synonym_m_D_glucose_6_phosphate_m_alpha_D_Glucose_6_phosphate_c_m, axiom, ( met(m_D_glucose_6_phosphate, c_m) | ~met(m_alpha_D_Glucose_6_phosphate, c_m) )).
cnf(synonym_m_alpha_D_Glucose_6_phosphate_m_D_glucose_6_phosphate_c_m, axiom, ( met(m_alpha_D_Glucose_6_phosphate, c_m) | ~met(m_D_glucose_6_phosphate, c_m) )).
cnf(synonym_m_D_glucose_6_phosphate_m_alpha_D_Glucose_6_phosphate_c_n, axiom, ( met(m_D_glucose_6_phosphate, c_n) | ~met(m_alpha_D_Glucose_6_phosphate, c_n) )).
cnf(synonym_m_alpha_D_Glucose_6_phosphate_m_D_glucose_6_phosphate_c_n, axiom, ( met(m_alpha_D_Glucose_6_phosphate, c_n) | ~met(m_D_glucose_6_phosphate, c_n) )).
cnf(synonym_m_D_glucose_6_phosphate_m_alpha_D_Glucose_6_phosphate_c_p, axiom, ( met(m_D_glucose_6_phosphate, c_p) | ~met(m_alpha_D_Glucose_6_phosphate, c_p) )).
cnf(synonym_m_alpha_D_Glucose_6_phosphate_m_D_glucose_6_phosphate_c_p, axiom, ( met(m_alpha_D_Glucose_6_phosphate, c_p) | ~met(m_D_glucose_6_phosphate, c_p) )).
cnf(synonym_m_D_glucose_6_phosphate_m_alpha_D_Glucose_6_phosphate_c_er, axiom, ( met(m_D_glucose_6_phosphate, c_er) | ~met(m_alpha_D_Glucose_6_phosphate, c_er) )).
cnf(synonym_m_alpha_D_Glucose_6_phosphate_m_D_glucose_6_phosphate_c_er, axiom, ( met(m_alpha_D_Glucose_6_phosphate, c_er) | ~met(m_D_glucose_6_phosphate, c_er) )).
cnf(synonym_m_D_glucose_6_phosphate_m_alpha_D_Glucose_6_phosphate_c_g, axiom, ( met(m_D_glucose_6_phosphate, c_g) | ~met(m_alpha_D_Glucose_6_phosphate, c_g) )).
cnf(synonym_m_alpha_D_Glucose_6_phosphate_m_D_glucose_6_phosphate_c_g, axiom, ( met(m_alpha_D_Glucose_6_phosphate, c_g) | ~met(m_D_glucose_6_phosphate, c_g) )).
cnf(synonym_m_D_glucose_6_phosphate_m_alpha_D_Glucose_6_phosphate_c_lp, axiom, ( met(m_D_glucose_6_phosphate, c_lp) | ~met(m_alpha_D_Glucose_6_phosphate, c_lp) )).
cnf(synonym_m_alpha_D_Glucose_6_phosphate_m_D_glucose_6_phosphate_c_lp, axiom, ( met(m_alpha_D_Glucose_6_phosphate, c_lp) | ~met(m_D_glucose_6_phosphate, c_lp) )).
cnf(synonym_m_D_glucose_6_phosphate_m_alpha_D_Glucose_6_phosphate_c_v, axiom, ( met(m_D_glucose_6_phosphate, c_v) | ~met(m_alpha_D_Glucose_6_phosphate, c_v) )).
cnf(synonym_m_alpha_D_Glucose_6_phosphate_m_D_glucose_6_phosphate_c_v, axiom, ( met(m_alpha_D_Glucose_6_phosphate, c_v) | ~met(m_D_glucose_6_phosphate, c_v) )).
cnf(synonym_m_D_glucose_6_phosphate_m_alpha_D_Glucose_6_phosphate_c_erm, axiom, ( met(m_D_glucose_6_phosphate, c_erm) | ~met(m_alpha_D_Glucose_6_phosphate, c_erm) )).
cnf(synonym_m_alpha_D_Glucose_6_phosphate_m_D_glucose_6_phosphate_c_erm, axiom, ( met(m_alpha_D_Glucose_6_phosphate, c_erm) | ~met(m_D_glucose_6_phosphate, c_erm) )).
cnf(synonym_m_D_glucose_6_phosphate_m_alpha_D_Glucose_6_phosphate_c_vm, axiom, ( met(m_D_glucose_6_phosphate, c_vm) | ~met(m_alpha_D_Glucose_6_phosphate, c_vm) )).
cnf(synonym_m_alpha_D_Glucose_6_phosphate_m_D_glucose_6_phosphate_c_vm, axiom, ( met(m_alpha_D_Glucose_6_phosphate, c_vm) | ~met(m_D_glucose_6_phosphate, c_vm) )).
cnf(synonym_m_D_glucose_6_phosphate_m_alpha_D_Glucose_6_phosphate_c_gm, axiom, ( met(m_D_glucose_6_phosphate, c_gm) | ~met(m_alpha_D_Glucose_6_phosphate, c_gm) )).
cnf(synonym_m_alpha_D_Glucose_6_phosphate_m_D_glucose_6_phosphate_c_gm, axiom, ( met(m_alpha_D_Glucose_6_phosphate, c_gm) | ~met(m_D_glucose_6_phosphate, c_gm) )).
cnf(synonym_m_D_glucose_6_phosphate_m_alpha_D_Glucose_6_phosphate_c_mm, axiom, ( met(m_D_glucose_6_phosphate, c_mm) | ~met(m_alpha_D_Glucose_6_phosphate, c_mm) )).
cnf(synonym_m_alpha_D_Glucose_6_phosphate_m_D_glucose_6_phosphate_c_mm, axiom, ( met(m_alpha_D_Glucose_6_phosphate, c_mm) | ~met(m_D_glucose_6_phosphate, c_mm) )).
