%----- METABOLITE PRESENCE (MEDIA) (R)-pantothenate (extracellular)
cnf(m__R__pantothenate_MEDIA_c_e, axiom, ( met(m__R__pantothenate, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) 4-aminobenzoate (extracellular)
cnf(m_4_aminobenzoate_MEDIA_c_e, axiom, ( met(m_4_aminobenzoate, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) ammonium (extracellular)
cnf(m_ammonium_MEDIA_c_e, axiom, ( met(m_ammonium, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) biotin (extracellular)
cnf(m_biotin_MEDIA_c_e, axiom, ( met(m_biotin, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) ethanol (extracellular)
cnf(m_ethanol_MEDIA_c_e, axiom, ( met(m_ethanol, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) folate (extracellular)
cnf(m_folate_MEDIA_c_e, axiom, ( met(m_folate, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) H+ (extracellular)
cnf(m_H__MEDIA_c_e, axiom, ( met(m_H_, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) H2O (extracellular)
cnf(m_H2O_MEDIA_c_e, axiom, ( met(m_H2O, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) L-histidine (extracellular)
cnf(m_L_histidine_MEDIA_c_e, axiom, ( met(m_L_histidine, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) L-leucine (extracellular)
cnf(m_L_leucine_MEDIA_c_e, axiom, ( met(m_L_leucine, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) myo-inositol (extracellular)
cnf(m_myo_inositol_MEDIA_c_e, axiom, ( met(m_myo_inositol, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) nicotinate (extracellular)
cnf(m_nicotinate_MEDIA_c_e, axiom, ( met(m_nicotinate, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) phosphate (extracellular)
cnf(m_phosphate_MEDIA_c_e, axiom, ( met(m_phosphate, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) potassium (extracellular)
cnf(m_potassium_MEDIA_c_e, axiom, ( met(m_potassium, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) pyridoxine (extracellular)
cnf(m_pyridoxine_MEDIA_c_e, axiom, ( met(m_pyridoxine, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) riboflavin (extracellular)
cnf(m_riboflavin_MEDIA_c_e, axiom, ( met(m_riboflavin, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) sodium (extracellular)
cnf(m_sodium_MEDIA_c_e, axiom, ( met(m_sodium, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) sulphate (extracellular)
cnf(m_sulphate_MEDIA_c_e, axiom, ( met(m_sulphate, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) thiamine (extracellular)
cnf(m_thiamine_MEDIA_c_e, axiom, ( met(m_thiamine, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) uracil (extracellular)
cnf(m_uracil_MEDIA_c_e, axiom, ( met(m_uracil, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) Mn(2+) (extracellular)
cnf(m_Mn_2___MEDIA_c_e, axiom, ( met(m_Mn_2__, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) Zn(2+) (extracellular)
cnf(m_Zn_2___MEDIA_c_e, axiom, ( met(m_Zn_2__, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) iron(3+) (extracellular)
cnf(m_iron_3___MEDIA_c_e, axiom, ( met(m_iron_3__, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) Ca(2+) (extracellular)
cnf(m_Ca_2___MEDIA_c_e, axiom, ( met(m_Ca_2__, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) Mg(2+) (extracellular)
cnf(m_Mg_2___MEDIA_c_e, axiom, ( met(m_Mg_2__, c_e) )).
%----- METABOLITE PRESENCE (MEDIA) Cu2(+) (extracellular)
cnf(m_Cu2____MEDIA_c_e, axiom, ( met(m_Cu2___, c_e) )).
